# Generated by Django 5.1.7 on 2025-04-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='delete',
            new_name='delete_at',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='delete',
            new_name='delete_at',
        ),
    ]
