# Generated by Django 5.1.7 on 2025-04-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_delete_customuser_delete_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="birthday",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата рождения"
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Город"
            ),
        ),
    ]
