# Generated by Django 5.1.7 on 2025-04-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userdata_birthday_userdata_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="fio",
        ),
    ]
