version: "3.9"

services:
  django:
    env_file:
      - .env
    build:
      context: .
    command: >
      sh -c "poetry run python manage.py migrate &&
             poetry run python manage.py collectstatic --noinput &&
             poetry run python manage.py create_superuser &&
             poetry run uvicorn clo.asgi:application --host 0.0.0.0 --port 8000"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static:/app/staticfiles
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  postgres_data:
