global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'
    basic_auth:
      username: '79627752922'
      password: 'SpaseWarp755//\\..'