# Generated by Django 5.1.7 on 2025-03-28 13:25

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='products/images/%Y/%m/%d/'),
        ),
    ]
