# Generated by Django 5.1.7 on 2025-04-02 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_favoriteproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.colors', verbose_name='Цвет'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.categories', verbose_name='Категория'),
        ),
    ]
