# Generated by Django 5.1.7 on 2025-04-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_brands_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='delete',
            new_name='delete_at',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='delete',
            new_name='delete_at',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='delete',
            new_name='delete_at',
        ),
        migrations.RenameField(
            model_name='colors',
            old_name='delete',
            new_name='delete_at',
        ),
        migrations.RenameField(
            model_name='favoriteproduct',
            old_name='delete',
            new_name='delete_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='delete',
            new_name='delete_at',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='delete',
            new_name='delete_at',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='delete',
            new_name='delete_at',
        ),
        migrations.RenameField(
            model_name='sizes',
            old_name='delete',
            new_name='delete_at',
        ),
    ]
