# Generated by Django 5.1.7 on 2025-04-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_product_brands_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="sizes",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Мужчина"), ("FEMALE", "Женщина")],
                max_length=10,
                null=True,
            ),
        ),
    ]
