# Generated by Django 5.1.7 on 2025-04-14 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_shop_icon_alter_productimages_image_shopimages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "delete_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время удаления"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название магазина",
                    ),
                ),
                (
                    "social_media",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Социальная сеть",
                    ),
                ),
                (
                    "portfolio",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Портфолио"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "ShopReport",
                "verbose_name_plural": "ShopReports",
                "db_table": "clo_shop_report",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
