# Generated by Django 5.1.7 on 2025-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_shopreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="brands",
            name="key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
