# Generated by Django 5.1.7 on 2025-04-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_brands_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="shop",
        ),
        migrations.AddField(
            model_name="shop",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shop.address",
                verbose_name="Адресс",
            ),
        ),
    ]
