# Generated by Django 5.1.7 on 2025-04-17 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_remove_address_shop_shop_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "delete_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время удаления"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        max_length=5, verbose_name="Оценка"
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductRating",
                "verbose_name_plural": "ProductRating",
                "db_table": "clo_product_rating",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShopRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "delete_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время удаления"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        max_length=5, verbose_name="Оценка"
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "ShopRating",
                "verbose_name_plural": "ShopRating",
                "db_table": "clo_shop_rating",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShopWorkSchedules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "delete_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время удаления"
                    ),
                ),
                (
                    "work_schedule",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Время работы"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "ShopWorkSchedules",
                "verbose_name_plural": "ShopWorkSchedules",
                "db_table": "clo_shop_work_schedules",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
