# Generated by Django 5.1.7 on 2025-04-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_alter_productrating_rating_alter_shoprating_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrating",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="shop.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="shoprating",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="shop.shop",
                verbose_name="Магазин",
            ),
        ),
    ]
