# Generated by Django 5.1.7 on 2025-04-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_alter_productrating_product_alter_shoprating_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="additional_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Дополнительная информация"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="additional_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Дополнительная информация"
            ),
        ),
    ]
