# Generated by Django 5.1.7 on 2025-04-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_product_additional_data_shop_additional_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopworkschedules",
            name="shop",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_schedules",
                to="shop.shop",
            ),
        ),
    ]
