# Generated by Django 5.1.7 on 2025-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_shopworkschedules_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
