# Generated by Django 5.1.7 on 2025-04-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_shop_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Артикул товара"
            ),
        ),
    ]
