# Generated by Django 5.1.7 on 2025-05-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0026_product_external_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "delete_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время удаления"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название образа",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="цена"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "HumanImage",
                "verbose_name_plural": "HumanImages",
                "db_table": "clo_human_images",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductHumanImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "human_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.humanimage",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
                (
                    "product_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.colors"
                    ),
                ),
                (
                    "product_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productimages",
                    ),
                ),
            ],
            options={
                "verbose_name": "ProductHumanImage",
                "verbose_name_plural": "ProductHumanImages",
                "db_table": "clo_product_human_images",
            },
        ),
        migrations.AddField(
            model_name="humanimage",
            name="products",
            field=models.ManyToManyField(
                related_name="human_image",
                through="shop.ProductHumanImages",
                to="shop.product",
                verbose_name="Продукты",
            ),
        ),
    ]
