# Generated by Django 5.1.7 on 2025-05-17 08:48

import django.db.models.deletion
import storages.backends.s3
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0027_humanimage_producthumanimages_humanimage_products"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanImageImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего обновления"
                    ),
                ),
                (
                    "delete_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время удаления"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(),
                        upload_to="shop/images/%Y-%m-%d/",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
                (
                    "human_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.humanimage",
                        verbose_name="Образ",
                    ),
                ),
            ],
            options={
                "verbose_name": "HumanImageImage",
                "verbose_name_plural": "HumanImageImages",
                "db_table": "clo_human_image_images",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
