# Generated by Django 5.1.7 on 2025-05-25 15:06
import random

from django.db import migrations, models
from django.db import transaction


def set_external_id(apps, schema_editor):
    with transaction.atomic():
        Product = apps.get_model("shop", "Product")
        products = Product.objects.all().only("id", "external_id")
        update_products = []

        for product in products:
            product.external_id = random.randint(10_000_000, 99_999_999)
            update_products.append(product)

        Product.objects.bulk_update(update_products, ["external_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0028_humanimageimages"),
    ]
    operations = [
        migrations.RunPython(
            code=set_external_id,
        ),
        migrations.AlterField(
            model_name="product",
            name="external_id",
            field=models.CharField(
                db_index=True, max_length=10, unique=True, verbose_name="Артикул товара"
            ),
        ),
    ]
