# Generated by Django 5.1.7 on 2025-05-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0029_alter_product_external_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavoriteProduct",
        ),
    ]
