# Generated by Django 5.1.7 on 2025-05-28 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0031_favoriteproduct"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteProduct",
            new_name="CustomUserFavoriteProduct",
        ),
        migrations.RenameField(
            model_name="shoprating",
            old_name="product",
            new_name="shop",
        ),
    ]
