# Generated by Django 5.1.7 on 2025-05-28 17:01

from django.conf import settings
from django.db import migrations, transaction


def create_test_users(apps, schema_editor):
    with transaction.atomic():
        CustomUser = apps.get_model("users", "CustomUser")
        Group = apps.get_model("auth", "Group")
        is_admin_group, is_admin_created = Group.objects.get_or_create(name="IsAdmin")
        is_owner_group, is_owner_created = Group.objects.get_or_create(name="IsOwner")
        is_user_group, is_user_created = Group.objects.get_or_create(name="IsUser")

        is_admin = CustomUser.objects.create(
            username="adminuser",
            phone="700000000001",
            first_name="first_name_is_admin",
            last_name="last_name_is_admin",
            middle_name="middle_name_is_admin",
            is_active=True,
        )
        is_owner = CustomUser.objects.create(
            username="owneruser",
            phone="700000000002",
            password="owner",
            first_name="first_name_is_owner",
            last_name="last_name_is_owner",
            middle_name="middle_name_is_owner",
            is_active=True,
        )
        is_user = CustomUser.objects.create(
            username="useruser",
            phone="700000000003",
            password="user",
            first_name="first_name_is_user",
            last_name="last_name_is_user",
            middle_name="middle_name_is_user",
            is_active=True,
        )

        is_admin_group.user_set.add(is_admin)
        is_owner_group.user_set.add(is_owner)
        is_user_group.user_set.add(is_user)
        is_admin_group.save()
        is_owner_group.save()
        is_user_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0032_rename_favoriteproduct_customuserfavoriteproduct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=create_test_users,
        )
    ]
