# Generated by Django 5.1.7 on 2025-06-05 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0033_auto_20250528_2001"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="from_is",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Создан откуда"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="portfolio",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Портфолио"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="social_media",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Социальная сеть"
            ),
        ),
        migrations.AddField(
            model_name="shopreport",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="shopreport",
            name="future_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shop_report",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="shopreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In Progress"),
                    ("APPROVE", "Approve"),
                    ("REJECTED", "Rejected"),
                ],
                default="IN_PROGRESS",
                max_length=50,
            ),
        ),
    ]
