# Generated by Django 5.1.7 on 2025-06-05 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0034_shop_from_is_shop_portfolio_shop_social_media_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopreport",
            name="future_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shop_report",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Будущий владелец",
            ),
        ),
    ]
