# Generated by Django 5.1.7 on 2025-06-08 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0035_alter_shopreport_future_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanimage",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_images",
                to="shop.shop",
                verbose_name="Магазин",
            ),
        ),
    ]
