# Generated by Django 5.1.7 on 2025-07-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0037_alter_product_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanimage",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Включен"),
        ),
    ]
