# Generated by Django 5.1.7 on 2025-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('delete', models.DateTimeField(blank=True, null=True, verbose_name='Время удаления')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность магазина')),
                ('status', models.CharField(choices=[('WORK', 'Work'), ('NOT_WORK', 'Not Work')], default='WORK', max_length=50)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'db_table': 'clo_shop',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
